services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos_db
      MAX_CONNECTIONS: 200
      SHARED_BUFFERS: 4GB

  api1:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/todos_db
      PORT: 3001
    command: sh -c "bun run db:setup && bun run start"

  api2:
    build: .
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/todos_db
      PORT: 3002
    command: sh -c "bun run db:setup && bun run start"

  api3:
    build: .
    ports:
      - "3003:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/todos_db
      PORT: 3003
    command: sh -c "bun run db:setup && bun run start"

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
      - api3

volumes:
  postgres_data: